function routerList() {
  return Promise.resolve({
    msg: "认证成功",
    code: 200,
    data: {
      cOpCde: "007",
      cOpCnm: "新非车理赔",
      cOpType: "0",
      cParentCde: "0",
      child: [
        {
          cOpCde: "007001",
          cOpCnm: "报案中心",
          cOpImg: "yewubaobiao",
          cOpType: "0",
          cParentCde: "007",
          child: [
            {
              cOpCde: "007001001",
              cOpCnm: "报案",
              cOpImg: "houtaiguanli",
              cOpType: "0",
              cParentCde: "007001",
              child: [
                {
                  cOpAct: "/index/rpt/queryPcis",
                  cOpCde: "007001001001",
                  // cOpRoot: "报案中心/报案",
                  cOpCnm: "新增报案",
                  cOpType: "0",
                  cParentCde: "007001001",
                  child: [],
                  nOpOrder: 0,
                },
                {
                  cOpAct: "/index/rpt/queryRptModify",
                  cOpCde: "007001001003",
                  cOpCnm: "暂存报案查询",
                  cOpType: "0",
                  cParentCde: "007001001",
                  child: [],
                  nOpOrder: 1,
                },
                {
                  cOpAct: "/index/rpt/batchClaim",
                  cOpCde: "007001001004",
                  cOpCnm: "批量理赔",

                  cOpType: "0",
                  cParentCde: "007001001",
                  child: [],
                  nOpOrder: 2,
                },
                {
                  cOpAct: "/index/rpt/queryRpt",
                  cOpCde: "007001001002",
                  cOpCnm: "已报案查询",

                  cOpType: "0",
                  cParentCde: "007001001",
                  child: [],
                  nOpOrder: 3,
                },
              ],
              nOpOrder: 0,
            },
          ],
          nOpOrder: 0,
        },
        {
          cOpCde: "007002",
          cOpCnm: "理赔中心",
          cOpImg: "liuchengshenpi",
          cOpType: "0",
          cParentCde: "007",
          child: [
            {
              cOpCde: "007002001",
              cOpCnm: "调度中心",
              cOpType: "0",
              cParentCde: "007002",
              child: [
                {
                  cOpAct: "/index/dspt/dsptquery",
                  cOpCde: "007002001001",
                  cOpCnm: "调度任务",
                  cOpType: "0",
                  cParentCde: "007002001",
                  child: [],
                  nOpOrder: 0,
                },
                {
                  cOpAct: "/dspt/dsptquery/detail",
                  menuPath: '/dspt/dsptquery',
                  cOpCnm: "调度任务详情",
                  cOpType: "0",
                  cParentCde: "007002001",
                  child: [],
                  nOpOrder: 0,
                },
                {
                  cOpAct: "/index/dspt-Taskchg/taskquery",
                  cOpCde: "007002001002",
                  cOpCnm: "直接改派",
                  cOpType: "0",
                  cParentCde: "007002001",
                  child: [],
                  nOpOrder: 1,
                },
              ],
              nOpOrder: 0,
            },
            {
              cOpCde: "007002002",
              cOpCnm: "查勘定损管理",
              cOpType: "0",
              cParentCde: "007002",
              child: [
                {
                  cOpAct: "index/survyloss/newSurveylossList",
                  cOpCde: "007002002001",
                  cOpCnm: "查勘定损任务",
                  cOpType: "0",
                  cParentCde: "007002002",
                  child: [],
                  nOpOrder: 0,
                },
                {
                  cOpAct: "index/survylosssimplecase/simpleCasePend",
                  cOpCde: "007002002002",
                  cOpCnm: "简易案件",
                  cOpType: "0",
                  cParentCde: "007002002",
                  child: [],
                  nOpOrder: 1,
                },
              ],
              nOpOrder: 1,
            },
            {
              cOpCde: "007002010",
              cOpCnm: "调查",
              cOpType: "0",
              cParentCde: "007002",
              child: [
                {
                  cOpAct: "/index/suspicious/investigationCaseQuery",
                  cOpCde: "007002010004",
                  cOpCnm: "案件调查",
                  cOpType: "0",
                  cParentCde: "007002010",
                  child: [],
                  nOpOrder: 4,
                },
              ],
              nOpOrder: 2,
            },
            {
              cOpCde: "007002003",
              cOpCnm: "立案管理",
              cOpType: "0",
              cParentCde: "007002",
              child: [
                {
                  cOpAct: "index/register/registerlist",
                  cOpCde: "007002003001",
                  cOpCnm: "立案任务",
                  cOpType: "0",
                  cParentCde: "007002003",
                  child: [],
                  nOpOrder: 0,
                },
              ],
              nOpOrder: 3,
            },
            {
              cOpCde: "007002004",
              cOpCnm: "案件跟踪",
              cOpType: "0",
              cParentCde: "007002",
              child: [
                {
                  cOpAct: "index/injuredtrack/injuredtrackList",
                  cOpCde: "007002004001",
                  cOpCnm: "案件跟踪任务",
                  cOpType: "0",
                  cParentCde: "007002004",
                  child: [],
                  nOpOrder: 0,
                },
              ],
              nOpOrder: 4,
            },
            {
              cOpCde: "007002006",
              cOpCnm: "理算中心",
              cOpType: "0",
              cParentCde: "007002",
              child: [
                {
                  cOpAct: "index/adjust/adjustquery",
                  cOpCde: "007002006001",
                  cOpCnm: "理算任务",
                  cOpType: "0",
                  cParentCde: "007002006",
                  child: [],
                  nOpOrder: 0,
                },
                {
                  cOpAct: "/index/paymentInformation/paymentInformationQuery",
                  cOpCde: "0070020060002",
                  cOpCnm: "反洗钱信息补录",
                  cOpType: "0",
                  cParentCde: "007002006",
                  child: [],
                  nOpOrder: 2,
                },
              ],
              nOpOrder: 6,
            },
            {
              cOpCde: "007002007",
              cOpCnm: "核赔管理",
              cOpType: "0",
              cParentCde: "007002",
              child: [
                {
                  cOpAct: "index/checkclaim/queryCheckclaim",
                  cOpCde: "007002007001",
                  cOpCnm: "核赔任务",
                  cOpType: "0",
                  cParentCde: "007002007",
                  child: [],
                  nOpOrder: 0,
                },
              ],
              nOpOrder: 11,
            },
            {
              cOpCde: "007002008",
              cOpCnm: "结案管理",
              cOpType: "0",
              cParentCde: "007002",
              child: [
                {
                  cOpAct: "index/endcase/waitendcase",
                  cOpCde: "007002008001",
                  cOpCnm: "结案任务",
                  cOpType: "0",
                  cParentCde: "007002008",
                  child: [],
                  nOpOrder: 0,
                },
              ],
              nOpOrder: 12,
            },
          ],
          nOpOrder: 1,
        },
        {
          cOpCde: "007003",
          cOpCnm: "理赔辅助服务",
          cOpImg: "xiaoshouguanli",
          cOpType: "0",
          cParentCde: "007",
          child: [
            {
              cOpCde: "007003001",
              cOpCnm: "撤销案管理",
              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "index/cancel/cancelapplist",
                  cOpCde: "007003001001",
                  cOpCnm: "立案注销申请",
                  cOpType: "0",
                  cParentCde: "007003001",
                  child: [],
                  nOpOrder: 0,
                },
                {
                  cOpAct: "index/cancel/cancelrecoverlist",
                  cOpCde: "007003001003",
                  cOpCnm: "立案注销恢复",
                  cOpType: "0",
                  cParentCde: "007003001",
                  child: [],
                  nOpOrder: 2,
                },
                {
                  cOpAct: "index/cancel/removeCaseList",
                  cOpCde: "007003001004",
                  cOpCnm: "报案注销申请",
                  cOpType: "0",
                  cParentCde: "007003001",
                  child: [],
                  nOpOrder: 3,
                },
                {
                  cOpAct: "index/cancel/cancelList",
                  cOpCde: "007003001005",
                  cOpCnm: "销案查询",
                  cOpType: "0",
                  cParentCde: "007003001",
                  child: [],
                  nOpOrder: 4,
                },
              ],
              nOpOrder: 0,
            },
            {
              cOpCde: "00700325",
              cOpCnm: "打假挤虚",
              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "/index/play-fakes/playFakesApplyQuery",
                  cOpCde: "00700325001",
                  cOpCnm: "打假挤虚申请",
                  cOpType: "0",
                  cParentCde: "00700325",
                  child: [],
                  nOpOrder: 0,
                },
                {
                  cOpAct: "/index/play-fakes/playFakesChkQuery",
                  cOpCde: "00700325002",
                  cOpCnm: "打假挤虚审核",
                  cOpType: "0",
                  cParentCde: "00700325",
                  child: [],
                  nOpOrder: 1,
                },
              ],
              nOpOrder: 0,
            },
            {
              cOpCde: "007003002",
              cOpCnm: "预付管理",
              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "index/prepay/newPrepayList",
                  cOpCde: "007003002001",
                  cOpCnm: "预付任务",
                  cOpType: "0",
                  cParentCde: "007003002",
                  child: [],
                  nOpOrder: 0,
                },
              ],
              nOpOrder: 1,
            },
            {
              cOpCde: "007003003",
              cOpCnm: "费用管理",
              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "index/feepay/feepayComponent",
                  cOpCde: "007003003001",
                  cOpCnm: "理赔费用申请",
                  cOpType: "0",
                  cParentCde: "007003003",
                  child: [],
                  nOpOrder: 0,
                },
                {
                  cOpAct: "index/feepay/feepayChkList",
                  cOpCde: "007003003002",
                  cOpCnm: "理赔费用审核",
                  cOpType: "0",
                  cParentCde: "007003003",
                  child: [],
                  nOpOrder: 1,
                },
              ],
              nOpOrder: 2,
            },
            {
              cOpCde: "007003004",
              cOpCnm: "重开案管理",
              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "/index/report/queryReportApp",
                  cOpCde: "007003004001",
                  cOpCnm: "重开案申请",
                  cOpType: "0",
                  cParentCde: "007003004",
                  child: [],
                  nOpOrder: 0,
                },
                {
                  cOpAct: "/index/report/queryReportChk",
                  cOpCde: "007003004002",
                  cOpCnm: "重开案审核",
                  cOpType: "0",
                  cParentCde: "007003004",
                  child: [],
                  nOpOrder: 1,
                },
              ],
              nOpOrder: 3,
            },
            {
              cOpCde: "007003005",
              cOpCnm: "追偿管理",
              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "index/recovery/recoveryRegister",
                  cOpCde: "007003005001",
                  cOpCnm: "追偿立案",
                  cOpType: "0",
                  cParentCde: "007003005",
                  child: [],
                  nOpOrder: 0,
                },
                {
                  cOpAct: "index/recovery/recoveryEnd",
                  cOpCde: "007003005002",
                  cOpCnm: "追偿结案",
                  cOpType: "0",
                  cParentCde: "007003005",
                  child: [],
                  nOpOrder: 1,
                },
                {
                  cOpAct: "index/recovery/completeRecovery",
                  cOpCde: "007003005003",
                  cOpCnm: "追偿查询",
                  cOpType: "0",
                  cParentCde: "007003005",
                  child: [],
                  nOpOrder: 2,
                },
              ],
              nOpOrder: 4,
            },
            {
              cOpCde: "007003006",
              cOpCnm: "诉讼管理",
              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "index/litigation/litigationRegisteList",
                  cOpCde: "007003006001",
                  cOpCnm: "诉前申请",
                  cOpType: "0",
                  cParentCde: "007003006",
                  child: [],
                  nOpOrder: 0,
                },
                {
                  cOpAct: "index/litigation/preLitigationAuditList",
                  cOpCde: "007003006004",
                  cOpCnm: "诉前审核",
                  cOpType: "0",
                  cParentCde: "007003006",
                  child: [],
                  nOpOrder: 4,
                },
                {
                  cOpAct: "index/litigation/litigationEndcaseList",
                  cOpCde: "007003006007",
                  cOpCnm: "诉讼结案",
                  cOpType: "0",
                  cParentCde: "007003006",
                  child: [],
                  nOpOrder: 7,
                },
                {
                  cOpAct: "index/litigation/litigationEndcaseAuditList",
                  cOpCde: "007003006008",
                  cOpCnm: "诉后审核",
                  cOpType: "0",
                  cParentCde: "007003006",
                  child: [],
                  nOpOrder: 8,
                },
              ],
              nOpOrder: 5,
            },
            {
              cOpCde: "007003011",
              cOpCnm: "理赔信息导入",

              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "index/claim-import/claimImport",
                  cOpCde: "007003011001",
                  cOpCnm: "信息导入",

                  cOpType: "0",
                  cParentCde: "007003011",
                  child: [],
                  nOpOrder: 1,
                },
                {
                  cOpAct: "index/claim-import/claimImportQueryList",
                  cOpCde: "007003011002",
                  cOpCnm: "已导入信息查询",

                  cOpType: "0",
                  cParentCde: "007003011",
                  child: [],
                  nOpOrder: 2,
                },
                {
                  cOpAct: "index/claim-import/newClaimImport",
                  cOpCde: "007003011003",
                  cOpCnm: "新赔案导入",

                  cOpType: "0",
                  cParentCde: "007003011",
                  child: [],
                  nOpOrder: 3,
                },
                {
                  cOpAct: "index/claim-import/newClaimImportCheck",
                  cOpCde: "007003011004",
                  cOpCnm: "赔案导入审核",

                  cOpType: "0",
                  cParentCde: "007003011",
                  child: [],
                  nOpOrder: 4,
                },
              ],
              nOpOrder: 6,
            },
            {
              cOpCde: "007003007",
              cOpCnm: "公告管理",
              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "index/bulletin",
                  cOpCde: "007003007001",
                  cOpCnm: "公告发布",

                  cOpType: "0",
                  cParentCde: "007003007",
                  child: [],
                  nOpOrder: 1,
                },
              ],
              nOpOrder: 7,
            },
            {
              cOpCde: "007003012",
              cOpCnm: "退票管理",

              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "index/ticket-return/payUpdateQuery",
                  cOpCde: "007003012001",
                  cOpCnm: "退票修改",

                  cOpType: "0",
                  cParentCde: "007003012",
                  child: [],
                  nOpOrder: 0,
                },
                {
                  cOpAct: "index/ticket-return/payCheckQuery",
                  cOpCde: "007003012002",
                  cOpCnm: "退票审核",

                  cOpType: "0",
                  cParentCde: "007003012",
                  child: [],
                  nOpOrder: 1,
                },
                {
                  cOpAct: "index/ticket-return/inquiryHisQuery",
                  cOpCde: "007003012003",
                  cOpCnm: "退票查询",

                  cOpType: "0",
                  cParentCde: "007003012",
                  child: [],
                  nOpOrder: 2,
                },
              ],
              nOpOrder: 7,
            },
            {
              cOpCde: "007003008",
              cOpCnm: "会商管理",
              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "index/counsel/counselDealQuery",
                  cOpCde: "007003008001",
                  cOpCnm: "会商处理",
                  cOpType: "0",
                  cParentCde: "007003008",
                  child: [],
                  nOpOrder: 0,
                },
                {
                  cOpAct: "/index/counsel/counselAppQuery",
                  cOpCde: "007003008002",
                  cOpCnm: "发起会商",

                  cOpType: "0",
                  cParentCde: "007003008",
                  child: [],
                  nOpOrder: 1,
                },
              ],
              nOpOrder: 8,
            },
            {
              cOpCde: "00700314",
              cOpCnm: "单证管理",
              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "index/documentmanagement/documentPrinting",
                  cOpCde: "00700314001",
                  cOpCnm: "单证打印",

                  cOpType: "0",
                  cParentCde: "00700314",
                  child: [],
                  nOpOrder: 1,
                },
              ],
              nOpOrder: 12,
            },
            {
              cOpCde: "00700315",
              cOpCnm: "未决管理",
              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "index/register/rgstamtmodifylist",
                  cOpCde: "00700315001",
                  cOpCnm: "估损调整",

                  cOpType: "0",
                  cParentCde: "00700315",
                  child: [],
                  nOpOrder: 1,
                },
                {
                  cOpAct: "index/pendingcheck/pendingcheckquery",
                  cOpCde: "00700315002",
                  cOpCnm: "估损调整审核",

                  cOpType: "0",
                  cParentCde: "00700315",
                  child: [],
                  nOpOrder: 2,
                },
                {
                  cOpAct: "index/register/rgstamtmodifylist",
                  cOpCde: "00700315003",
                  cOpCnm: "未决金额调整",
                  cOpType: "0",
                  cParentCde: "00700315",
                  child: [],
                  nOpOrder: 3,
                },
              ],
              nOpOrder: 13,
            },
            {
              cOpCde: "00700319",
              cOpCnm: "案件改派",
              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "index/reassignment/reassignmentQuery",
                  cOpCde: "00700319001",
                  cOpCnm: "改派任务",

                  cOpType: "0",
                  cParentCde: "00700319",
                  child: [],
                  nOpOrder: 1,
                },
              ],
              nOpOrder: 17,
            },
            {
              cOpCde: "00700320",
              cOpCnm: "质检管理",
              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "index/inspect/inspectQuery",
                  cOpCde: "00700320001",
                  cOpCnm: "质检",

                  cOpType: "0",
                  cParentCde: "00700320",
                  child: [],
                  nOpOrder: 1,
                },
                {
                  cOpAct: "index/inspect/inspectExport",
                  cOpCde: "00700320002",
                  cOpCnm: "质检结果导出",

                  cOpType: "0",
                  cParentCde: "00700320",
                  child: [],
                  nOpOrder: 2,
                },
              ],
              nOpOrder: 18,
            },
            {
              cOpCde: "00700323",
              cOpCnm: "延时报案",
              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "/index/delay-rpt/delayrptapplylist",
                  cOpCde: "00700323001",
                  cOpCnm: "延时报案申请",
                  cOpType: "0",
                  cParentCde: "00700323",
                  child: [],
                  nOpOrder: 0,
                },
                {
                  cOpAct: "/index/delay-rpt/delayrptchklist",
                  cOpCde: "00700323002",
                  cOpCnm: "延时报案审核",
                  cOpType: "0",
                  cParentCde: "00700323",
                  child: [],
                  nOpOrder: 1,
                },
              ],
              nOpOrder: 23,
            },
            {
              cOpCde: "00700324",
              cOpCnm: "公估委派管理",
              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "index/appraisalassignment/appraisalassignmentapplist",
                  cOpCde: "00700324001",
                  cOpCnm: "公估委派申请",

                  cOpType: "0",
                  cParentCde: "00700324",
                  child: [],
                  nOpOrder: 1,
                },
                {
                  cOpAct: "index/appraisalassignment/appraisalassignmentchklist",
                  cOpCde: "00700324002",
                  cOpCnm: "公估委派审核",
                  cOpType: "0",
                  cParentCde: "00700324",
                  child: [],
                  nOpOrder: 2,
                },
              ],
              nOpOrder: 24,
            },
            {
              cOpCde: "00700327",
              cOpCnm: "共保分摊管理",
              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "index/ci-amortiza/query",
                  cOpCde: "0070032701",
                  cOpCnm: "共保分摊查询",

                  cOpType: "0",
                  cParentCde: "00700327",
                  child: [],
                  nOpOrder: 1,
                },
              ],
              nOpOrder: 27,
            },
            {
              cOpCde: "00700329",
              cOpCnm: "残值管理",
              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "/index/claim-Residual/query",
                  cOpCde: "0070032901",
                  cOpCnm: "残值申请",
                  cOpType: "0",
                  cParentCde: "00700329",
                  child: [],
                  nOpOrder: 1,
                },
                {
                  cOpAct: "/index/claim-Residual/chkQuery",
                  cOpCde: "0070032902",
                  cOpCnm: "残值审核",
                  cOpType: "0",
                  cParentCde: "00700329",
                  child: [],
                  nOpOrder: 2,
                },
              ],
              nOpOrder: 29,
            },
            {
              cOpCde: "00700330",
              cOpCnm: "大案上报管理",
              cOpType: "0",
              cParentCde: "007003",
              child: [
                {
                  cOpAct: "index/case-report/caseSubmit",
                  cOpCde: "0070033001",
                  cOpCnm: "大案上报处理",
                  cOpType: "0",
                  cParentCde: "00700330",
                  child: [],
                  nOpOrder: 1,
                },
                {
                  cOpAct: "index/case-report/caseUndr",
                  cOpCde: "0070033002",
                  cOpCnm: "大案上报审核",
                  cOpType: "0",
                  cParentCde: "00700330",
                  child: [],
                  nOpOrder: 2,
                },
              ],
              nOpOrder: 30,
            },
          ],
          nOpOrder: 2,
        },
        {
          cOpCde: "007016",
          cOpCnm: "系统配置",
          cOpImg: "houtaiguanli",
          cOpType: "0",
          cParentCde: "007",
          cTarget: "0",
          child: [
            {
              cOpCde: "007016001",
              cOpCnm: "权限菜单配置",

              cOpType: "0",
              cParentCde: "007016",
              cTarget: "0",
              child: [
                {
                  cOpAct: "/index/sys-right-basic/role",
                  cOpCde: "007016001001",
                  cOpCnm: "角色配置",

                  cOpType: "0",
                  cParentCde: "007016001",
                  cTarget: "0",
                  child: [],
                  nOpOrder: 1,
                },
                {
                  cOpAct: "/index/sys-right-basic/operate",
                  cOpCde: "007016001002",
                  cOpCnm: "角色操作权限配置",

                  cOpType: "0",
                  cParentCde: "007016001",
                  cTarget: "0",
                  child: [],
                  nOpOrder: 2,
                },
                {
                  cOpAct: "/index/sys-right-basic/roleusr",
                  cOpCde: "007016001003",
                  cOpCnm: "角色用户配置",
                  cOpType: "0",
                  cParentCde: "007016001",
                  cTarget: "0",
                  child: [],
                  nOpOrder: 3,
                },
                {
                  cOpAct: "/index/sys-right-basic/operator",
                  cOpCde: "007016001005",
                  cOpCnm: "操作员配置",
                  cOpType: "0",
                  cParentCde: "007016001",
                  cTarget: "0",
                  child: [],
                  nOpOrder: 5,
                },
                {
                  cOpAct: "/index/sys-right-basic/usrrole",
                  cOpCde: "007016001006",
                  cOpCnm: "操作员权限配置",
                  cOpType: "0",
                  cParentCde: "007016001",
                  cTarget: "0",
                  child: [],
                  nOpOrder: 6,
                },
                {
                  cOpAct: "/index/sys-right-basic/dptmgr",
                  cOpCde: "007016001007",
                  cOpCnm: "机构部门管理",
                  cOpType: "0",
                  cParentCde: "007016001",
                  cTarget: "0",
                  child: [],
                  nOpOrder: 7,
                },
                {
                  cOpAct: "/index/sys-right-basic/empmgr",
                  cOpCde: "007016001009",
                  cOpCnm: "员工管理",

                  cOpType: "0",
                  cParentCde: "007016001",
                  cTarget: "0",
                  child: [],
                  nOpOrder: 9,
                },
                {
                  cOpAct: "/index/sys-right-basic/opmgr",
                  cOpCde: "007016001010",
                  cOpCnm: "权限菜单配置",

                  cOpType: "0",
                  cParentCde: "007016001",
                  cTarget: "0",
                  child: [],
                  nOpOrder: 10,
                },
                {
                  cOpAct: "index/sys-right-basic/chkuwquery",
                  cOpCde: "00701600111",
                  cOpCnm: "核赔员渠道权限配置",

                  cOpType: "0",
                  cParentCde: "007016001",
                  child: [],
                  nOpOrder: 11,
                },
              ],
              nOpOrder: 0,
            },
            {
              cOpCde: "007016002",
              cOpCnm: "基础数据配置",
              cOpType: "0",
              cParentCde: "007016",
              child: [
                {
                  cOpAct: "/index/claim-auth-level/authLevelQuery",
                  cOpCde: "007016002001",
                  cOpCnm: "权限级别配置",
                  cOpType: "0",
                  cParentCde: "007016002",
                  child: [],
                  nOpOrder: 0,
                },
                {
                  cOpAct: "/index/claim-cat/catconfig",
                  cOpCde: "007016002002",
                  cOpCnm: "巨灾配置",
                  cOpType: "0",
                  cParentCde: "007016002",
                  child: [],
                  nOpOrder: 2,
                },
                {
                  cOpAct: "/index/sys-right-basic/dptmap",
                  cOpCde: "007016002003",
                  cOpCnm: "承保和理赔机构映射",
                  cOpType: "0",
                  cParentCde: "007016002",
                  child: [],
                  nOpOrder: 3,
                },
                {
                  cOpAct: "/index/claim-hospital/clmHospitalList",
                  cOpCde: "007016002004",
                  cOpCnm: "医院信息维护",
                  cOpType: "0",
                  cParentCde: "007016002",
                  child: [],
                  nOpOrder: 4,
                },
                {
                  cOpAct: "/index/claim-doc/docTypeConfig",
                  cOpCde: "007016002005",
                  cOpCnm: "意健险单证类型配置",
                  cOpType: "0",
                  cParentCde: "007016002",
                  child: [],
                  nOpOrder: 5,
                },
                {
                  cOpAct: "index/claim-doc-prop/docPropConfig",
                  cOpCde: "007016002007",
                  cOpCnm: "财产险单证类型配置",
                  cOpType: "0",
                  cParentCde: "007016002",
                  child: [],
                  nOpOrder: 6,
                },
                {
                  cOpAct: "index/register/autoregistersettinglist",
                  cOpCde: "007016002008",
                  cOpCnm: "自动立案规则设置",
                  cOpType: "0",
                  cParentCde: "007016002",
                  child: [],
                  nOpOrder: 7,
                },
                {
                  cOpAct: "index/clmDptLevel/claimDptQuery",
                  cOpCde: "007016002009",
                  cOpCnm: "理赔机构等级配置（机构级别）",
                  cOpType: "0",
                  cParentCde: "007016002",
                  child: [],
                  nOpOrder: 8,
                },
                {
                  cOpAct: "/index/claim-basic-config/Surgery",
                  cOpCde: "007016002010",
                  cOpCnm: "手术代码基础数据",
                  cOpType: "0",
                  cParentCde: "007016002",
                  child: [],
                  nOpOrder: 10,
                },
                {
                  cOpAct: "/index/claim-basic-config/disease",
                  cOpCde: "007016002011",
                  cOpCnm: "疾病基础数据",

                  cOpType: "0",
                  cParentCde: "007016002",
                  child: [],
                  nOpOrder: 11,
                },
                {
                  cOpAct: "/index/claim-basic-config/disabledLevel",
                  cOpCde: "007016002012",
                  cOpCnm: "疾病等级基础数据",

                  cOpType: "0",
                  cParentCde: "007016002",
                  child: [],
                  nOpOrder: 12,
                },
                {
                  cOpAct: "/index/claim-basic-config/Institutions",
                  cOpCde: "007016002013",
                  cOpCnm: "司法鉴定机构基础数据",

                  cOpType: "0",
                  cParentCde: "007016002",
                  child: [],
                  nOpOrder: 13,
                },
                {
                  cOpAct: "/index/claim-basic-config/Appraiser",
                  cOpCde: "007016002014",
                  cOpCnm: "司法鉴定人基础数据",

                  cOpType: "0",
                  cParentCde: "007016002",
                  child: [],
                  nOpOrder: 14,
                },
                {
                  cOpAct: "/index/claim-basic-config/InnjuryStandard",
                  cOpCde: "007016002015",
                  cOpCnm: "伤残评定标准基础数据",

                  cOpType: "0",
                  cParentCde: "007016002",
                  child: [],
                  nOpOrder: 15,
                },
                {
                  cOpAct: "/index/claim-basic-config/innjuryLevel",
                  cOpCde: "007016002016",
                  cOpCnm: "伤致残程度等级基础数据",

                  cOpType: "0",
                  cParentCde: "007016002",
                  child: [],
                  nOpOrder: 16,
                },
              ],
              nOpOrder: 1,
            },
            {
              cOpCde: "007016003",
              cOpCnm: "理赔理算配置中心",
              cOpType: "0",
              cParentCde: "007016",
              child: [
                {
                  cOpAct: "/index/claim-calc-settings/calcItem",
                  cOpCde: "007016003001",
                  cOpCnm: "理算因子配置",

                  cOpType: "0",
                  cParentCde: "007016003",
                  child: [],
                  nOpOrder: 0,
                },
                {
                  cOpAct: "/index/claim-calc-settings/calcFormula",
                  cOpCde: "007016003002",
                  cOpCnm: "理算公式配置",

                  cOpType: "0",
                  cParentCde: "007016003",
                  child: [],
                  nOpOrder: 1,
                },
              ],
              nOpOrder: 2,
            },
            {
              cOpCde: "007016004",
              cOpCnm: "风控配置管理",
              cOpType: "0",
              cParentCde: "007016",
              child: [
                {
                  cOpAct: "index/risk-rule-setting/ruleItem",
                  cOpCde: "007016004001",
                  cOpCnm: "规则因子配置",

                  cOpType: "0",
                  cParentCde: "007016004",
                  child: [],
                  nOpOrder: 1,
                },
                {
                  cOpAct: "index/risk-rule-setting/riskInfo",
                  cOpCde: "007016004002",
                  cOpCnm: "风险信息配置",

                  cOpType: "0",
                  cParentCde: "007016004",
                  child: [],
                  nOpOrder: 2,
                },
                {
                  cOpAct: "index/risk-rule-setting/riskRuleDtl",
                  cOpCde: "007016004004",
                  cOpCnm: "风险规则明细配置",

                  cOpType: "0",
                  cParentCde: "007016004",
                  child: [],
                  nOpOrder: 4,
                },
              ],
              nOpOrder: 4,
            },
            {
              cOpCde: "007016005",
              cOpCnm: "黑名单",
              cOpType: "0",
              cParentCde: "007016",
              child: [
                {
                  cOpAct: "index/blacklist-setting/blackItem",
                  cOpCde: "007016005001",
                  cOpCnm: "用户黑名单",
                  cOpType: "0",
                  cParentCde: "007016005",
                  child: [],
                  nOpOrder: 1,
                },
              ],
              nOpOrder: 5,
            },
            {
              cOpCde: "007016006",
              cOpCnm: "合作方管理",
              cOpType: "0",
              cParentCde: "007016",
              child: [
                {
                  cOpAct: "index/partner-mgr/partnerSetting",
                  cOpCde: "007016006001",
                  cOpCnm: "合作方配置",

                  cOpType: "0",
                  cParentCde: "007016006",
                  child: [],
                  nOpOrder: 1,
                },
                {
                  cOpAct: "index/partner-mgr/partnerServerEval",
                  cOpCde: "007016006002",
                  cOpCnm: "合作方服务评价",

                  cOpType: "0",
                  cParentCde: "007016006",
                  child: [],
                  nOpOrder: 2,
                },
                {
                  cOpAct: "index/partner-mgr/partnerMonitorIndicator",
                  cOpCde: "007016006003",
                  cOpCnm: "合作方监测指标",

                  cOpType: "0",
                  cParentCde: "007016006",
                  child: [],
                  nOpOrder: 3,
                },
              ],
              nOpOrder: 6,
            },
            {
              cOpCde: "007016007",
              cOpCnm: "知识库",
              cOpType: "0",
              cParentCde: "007016",
              child: [
                {
                  cOpAct: "index/kblist-setting/kbItem",
                  cOpCde: "007016007001",
                  cOpCnm: "知识库维护",
                  cOpType: "0",
                  cParentCde: "007016007",
                  child: [],
                  nOpOrder: 1,
                },
                {
                  cOpAct: "index/kblist-setting/kbQuery",
                  cOpCde: "007016007002",
                  cOpCnm: "知识库查看",
                  cOpType: "0",
                  cParentCde: "007016007",
                  child: [],
                  nOpOrder: 2,
                },
              ],
              nOpOrder: 7,
            },
            {
              cOpCde: "007016008",
              cOpCnm: "理赔大脑",

              cOpType: "0",
              cParentCde: "007016",
              child: [
                {
                  cOpAct: "index/process-definition/query",
                  cOpCde: "007016008002",
                  cOpCnm: "流程设置",

                  cOpType: "0",
                  cParentCde: "007016008",
                  child: [],
                  nOpOrder: 1,
                },
                {
                  cOpAct: "index/process-setting/proSetting",
                  cOpCde: "007016008001",
                  cOpCnm: "三角平衡",

                  cOpType: "0",
                  cParentCde: "007016008",
                  child: [],
                  nOpOrder: 2,
                },
              ],
              nOpOrder: 8,
            },
          ],
          nOpOrder: 9,
        },
      ],
      nOpOrder: 0,
    },
  });
}

function delMenupath(data) {
  // 先过滤掉带 menuPath 的项
  let filtered = data.filter(item => !item.menuPath);
  // 然后递归处理子菜单
  filtered.forEach(item => {
    if (item.child && item.child.length > 0) {
      delMenupath(item.child);
    }
  });

  // 用过滤后的数组替换原数组的内容
  data.length = 0;
  data.push(...filtered);

  return data;
}

function getMenulist() {
  return routerList().then(res => {
    console.log("🚀 ~ routerJson.js:1330 ~ response ~ res:", res);
    let response = res.data.child;
    console.log("🚀 ~ routerJson.js:1343 ~ routerList ~ delMenupath(response);:", delMenupath(response))

    return Promise.resolve(delMenupath(response))
  });
}

export default {
  routerList,
  getMenulist
};
